services:

  camaleao_web_bimgo.filetwigextensio:
      class: Camaleao\Web\BimgoBundle\Twig\Extension\FileExtension
      tags:
        - { name: twig.extension }

  camaleao_web_bimgo.menu.voter.request:
      class: Camaleao\Web\BimgoBundle\Menu\RequestVoter
      arguments:
          - @service_container
      tags:
          - { name: knp_menu.voter }
