camaleao_bimgo_site:
    resource: "@CamaleaoBimgoSiteBundle/Controller/"
    type:     annotation
    prefix:   /

camaleao_bimgo_admin:
    resource: "@CamaleaoBimgoAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

camaleao_bimgo_user:
    resource: "@CamaleaoBimgoUserBundle/Controller/"
    type:     annotation
    prefix:   /user

camaleao_bimgo_api:
    resource: "@CamaleaoBimgoApiBundle/Controller/"
    type:     annotation
    prefix:   /api/v1