security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  user_usuario_entrar
                check_path:  user_usuario_autenticar
                default_target_path: user_usuario_redirecionar
                always_use_default_target_path: true
            http_basic:
                realm: "Secured Demo Area"
            logout:
                path:   user_usuario_sair
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMINISTRADOR }

    providers:
        main:
          entity: { class: Camaleao\Bimgo\CoreBundle\Entity\Usuario, property: email }

    encoders:
        Camaleao\Bimgo\CoreBundle\Entity\Usuario:
          algorithm: md5
          encode_as_base64: false
          iterations: 0