services:
  camaleao_bimgo_core.url_friendly:
    class:     Camaleao\Bimgo\CoreBundle\Service\TextHelper

  camaleao_bimgo_core.push_notification:
    class:     Camaleao\Bimgo\CoreBundle\Service\PushNotification
    arguments: [@endroid.gcm.client, @doctrine.orm.entity_manager]
