parameters:
  push_notification.class: Camaleao\Bimgo\CoreBundle\Service\PushNotification

services:
  camaleao_bimgo_core.push_notification:
    class:     %push_notification.class%
    arguments: [@endroid.gcm.client, @doctrine.orm.entity_manager]

  camaleao_bimgo_core.filetwigextensio:
    class: Camaleao\Bimgo\CoreBundle\Twig\Extension\FileExtension
    tags:
      - { name: twig.extension }