services:
  camaleao_bimgo_user.action_listener:
      class: Camaleao\Bimgo\UserBundle\EventListener\UserListener
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
