services:
  camaleao_bimgo_api.action_listener:
          class: Camaleao\Bimgo\ApiBundle\EventListener\ApiListener
          arguments: ['%camaleao_bimgo_api%']
          tags:
              - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
